### ISSUE TITLE
Error "password and hash need to be strings"

### ISSUE THREAD

**Issue by pkrupicka** [eventum/dokuwiki-plugin-eventum#2]
Hi, do you have any idea, why plugin doesn't work and prints error?
> password and hash need to be strings

I'm using **DokuWiki 2017-02-19b** and **Eventum 3.1.8**.

**Comment by glensc** [comment]
and what version of the plugin?

**Comment by glensc** [comment]
i think you forgot to configure the plugin.

added section to readme:
https://github.com/eventum/dokuwiki-plugin-eventum#download-and-installation

**Comment by pkrupicka** [comment]
I did, it probably just took long for server to apply changes. Now i get another error.
> Didn't receive 200 OK from remote server. (HTTP/1.1 302 Found)

I use latest GitHub release.

**Comment by pkrupicka** [comment]
Nevermind, my bad. I forgot, that Eventum username is actually e-mail address.

**Comment by glensc** [comment]
302 redirect indicates that the url you used got redirected.

recheck your url. it should be root of your eventum installation.
